import type { INodeProperties } from 'n8n-workflow';

export const translateVideoDescription: INodeProperties[] = [
	{
		displayName: 'Video URL',
		name: 'videoUrl',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['video'],
				operation: ['translateVideo'],
			},
		},
		default: '',
		description: 'URL of the video to translate',
	},
	{
		displayName: 'Audio URL',
		name: 'audioUrl',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['video'],
				operation: ['translateVideo'],
			},
		},
		default: '',
		description: 'Optional audio URL (alternative to video)',
	},
	{
		displayName: 'Output Language',
		name: 'outputLanguage',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['video'],
				operation: ['translateVideo'],
				useMultipleLanguages: [false],
			},
		},
		default: '',
		description: 'Target language code (e.g., "en", "es", "fr"). Use this for single output language.',
	},
	{
		displayName: 'Use Multiple Languages',
		name: 'useMultipleLanguages',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['video'],
				operation: ['translateVideo'],
			},
		},
		default: false,
		description: 'Whether to translate to multiple languages',
	},
	{
		displayName: 'Output Languages',
		name: 'outputLanguages',
		type: 'string',
		typeOptions: {
			multipleValues: true,
		},
		displayOptions: {
			show: {
				resource: ['video'],
				operation: ['translateVideo'],
				useMultipleLanguages: [true],
			},
		},
		default: [],
		description: 'Target language codes for multiple outputs (e.g., ["en", "es", "fr"])',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['video'],
				operation: ['translateVideo'],
			},
		},
		options: [
			{
				displayName: 'Brand Voice ID',
				name: 'brandVoiceId',
				type: 'string',
				default: '',
				description: 'Brand voice ID for TTS',
			},
			{
				displayName: 'Callback ID',
				name: 'callbackId',
				type: 'string',
				default: '',
				description: 'ID for webhook callbacks',
			},
			{
				displayName: 'Callback URL',
				name: 'callbackUrl',
				type: 'string',
				default: '',
				description: 'Webhook URL for completion notifications',
			},
			{
				displayName: 'Check Credits Sync',
				name: 'checkCreditsSync',
				type: 'boolean',
				default: false,
				description: 'Whether to check credits synchronization',
			},
			{
				displayName: 'Create Collection',
				name: 'createCollection',
				type: 'boolean',
				default: false,
				description: 'Whether to create a collection for multiple outputs',
			},
			{
				displayName: 'Disable Music Track',
				name: 'disableMusicTrack',
				type: 'boolean',
				default: false,
				description: 'Whether to disable background music',
			},
			{
				displayName: 'Enable Caption',
				name: 'enableCaption',
				type: 'boolean',
				default: false,
				description: 'Whether to enable captions/subtitles',
			},
			{
				displayName: 'Enable Dynamic Duration',
				name: 'enableDynamicDuration',
				type: 'boolean',
				default: true,
				description: 'Whether to enable dynamic duration adjustment',
			},
			{
				displayName: 'Enable Speech Enhancement',
				name: 'enableSpeechEnhancement',
				type: 'boolean',
				default: false,
				description: 'Whether to enable speech enhancement',
			},
			{
				displayName: 'Enable Watermark',
				name: 'enableWatermark',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'End Time',
				name: 'endTime',
				type: 'number',
				default: 0,
				description: 'End time in seconds for trimming',
			},
			{
				displayName: 'Folder ID',
				name: 'folderId',
				type: 'string',
				default: '',
				description: 'Project/folder ID to organize videos',
			},
			{
				displayName: 'FPS Mode',
				name: 'fpsMode',
				type: 'options',
				options: [
					{ name: 'VFR', value: 'vfr' },
					{ name: 'CFR', value: 'cfr' },
					{ name: 'Passthrough', value: 'passthrough' },
				],
				default: 'vfr',
				description: 'FPS mode: "vfr", "cfr", or "passthrough"',
			},
			{
				displayName: 'Input Language',
				name: 'inputLanguage',
				type: 'string',
				default: '',
				description: 'Source language code',
			},
			{
				displayName: 'Keep the Same Format',
				name: 'keepTheSameFormat',
				type: 'boolean',
				default: true,
			},
			{
				displayName: 'Mode',
				name: 'mode',
				type: 'options',
				options: [
					{ name: 'Fast', value: 'fast' },
					{ name: 'Quality', value: 'quality' },
					{ name: 'Speed', value: 'speed' },
					{ name: 'Precision', value: 'precision' },
				],
				default: 'fast',
				description: 'Processing mode: "fast", "quality", "speed", or "precision"',
			},
			{
				displayName: 'Speaker Number',
				name: 'speakerNum',
				type: 'number',
				default: 0,
				description: 'Number of speakers in the video',
			},
			{
				displayName: 'SRT Role',
				name: 'srtRole',
				type: 'options',
				options: [
					{ name: 'Input', value: 'input' },
					{ name: 'Output', value: 'output' },
				],
				default: 'input',
				description: 'SRT role: "input" or "output"',
			},
			{
				displayName: 'SRT URL',
				name: 'srtUrl',
				type: 'string',
				default: '',
				description: 'SRT subtitle file URL (Enterprise only)',
			},
			{
				displayName: 'Start Time',
				name: 'startTime',
				type: 'number',
				default: 0,
				description: 'Start time in seconds for trimming',
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: 'Title for the translated video',
			},
			{
				displayName: 'Translate Audio Only',
				name: 'translateAudioOnly',
				type: 'boolean',
				default: false,
				description: 'Whether to only translate audio',
			},
			{
				displayName: 'Use Disguised Voice',
				name: 'useDisguisedVoice',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Validate Only',
				name: 'validateOnly',
				type: 'boolean',
				default: false,
				description: 'Whether to only validate input without creating job',
			},
		],
	},
];


